name: Build and Deploy backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create env file
        run: |
          touch ./backend/.env
          echo DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }} >> ./backend/.env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> ./backend/.env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> ./backend/.env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> ./backend/.env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> ./backend/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ./backend/.env
          echo APP_KEYS=${{ secrets.APP_KEYS }} >> ./backend/.env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> ./backend/.env
          echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} >> ./backend/.env

      - name: Build and push Docker Compose Image
        run: |
          docker compose --file ./backend/docker-compose.yml build
      #     docker compose --file ./backend/docker-compose.yml push

      - name: Copy deployment script
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.DELTA_SSH_HOST }}
          username: ${{ secrets.DELTA_SSH_USER }}
          port: ${{ secrets.DELTA_SSH_PORT }}
          key: ${{ secrets.DELTA_SSH_PRIVATE_KEY }}
          source: ./backend/scripts/deploy.sh
          target: ${{ secrets.DELTA_DEPLOY_PATH }}
        
      - name: Run deployment script
        run: ssh -p ${{ secrets.DELTA_SSH_PORT }} ${{ secrets.DELTA_SSH_USER }}@${{ secrets.DELTA_SSH_HOST }} "cd ${{ secrets.DELTA_DEPLOY_PATH }} && sh deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DELTA_SSH_PRIVATE_KEY }}g

