name: Build and Deploy backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        run: echo ${{ secrets.GHCR_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Compose Image
        run: |
          docker compose --file ./backend/docker-compose.yml build
          docker compose --file ./backend/docker-compose.yml push
      
      - name: Deploy to Ubuntu Server
        run: ssh alec@nolliebigspin.com -p 22296 'bash -s' < ~/projects/awinter-dev/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DELTA_SSH_PRIVATE_KEY }}g

